# Generated by Django 5.0.3 on 2024-03-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_boy_project_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='resume',
            field=models.TextField(default='un litle resume'),
            preserve_default=False,
        ),
    ]
